apiVersion: apps/v1
kind: Deployment
metadata:
  name: basketball-matchmaking-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basketball-matchmaking
  template:
    metadata:
      labels:
        app: basketball-matchmaking
    spec:
      containers:
        - image: lgaljo/rt_basketball_matchmaking:latest
          name: basketball-matchmaking
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://pg-events.clvqrwayazxs.eu-central-1.rds.amazonaws.com/matchmaking
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: postgres
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-pass
                  key: KUMULUZEE_DATASOURCES0_PASSWORD
          ports:
            - containerPort: 8085
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
---

apiVersion: v1
kind: Service
metadata:
  name: basketball-matchmaking
spec:
  type: LoadBalancer
  ports:
    - port: 8085
      protocol: TCP
      targetPort: server
  selector:
    app: basketball-matchmaking